### PR TITLE
fix issue #3776

### LINKED ISSUE #3776: orm.RawSeter does not support orm.Fielder
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
1.12.0

2. What operating system and processor architecture are you using (`go env`)?
1.12.1

3. What did you do?
```golang
type SharedStorage struct {
        ...
	StorageAttribute StorageAttr `orm:"column(storage_attribute);type(text)"`
}
type StorageAttr struct {
	FileSysId    string            `json:"fileSystemId"`
	StorageSize  string            `json:"storageSize"`
	MountDomain  string            `json:"mountDomain"`
	VolumeLabels map[string]string `json:"volumeLabels"`
}

var _ orm.Fielder = new(StorageAttr)

func (e *StorageAttr) String() string {
	var data []byte
	if e == nil {
		data, _ = json.Marshal(struct{}{})
	} else {
		data, _ = json.Marshal(e)
	}
	return string(data)
}

func (e *StorageAttr) FieldType() int {
	return orm.TypeTextField
}

func (e *StorageAttr) SetRaw(value interface{}) error {
	switch d := value.(type) {
	case string:
		return json.Unmarshal([]byte(d), e)
	case []byte:
		return json.Unmarshal(d, e)
	default:
		return fmt.Errorf("<JsonField.SetRaw> unknown value `%v`", value)
	}
}

func (e *StorageAttr) RawValue() interface{} {
	return e.String()
}
```

4. What did you expect to see?
orm.NewOrm().Raw("select * from dual").QueryRows(&rows)
this line of code should deserialize the StorageAttribute field with values.

5. What did you see instead?
however what I get is just an empty struct.

### PR DESCRIPTION
**Pull request by AllenX2018**
fixes #3776

fix the bug that `Fielder`'s `SetRaw` is not called when calling `orm.Raw()` to query from database

### CODE REVIEW

**Comment by AllenX2018** [comment]
Seems that the unit test will fail with postgresql. Pls wait and I will fix it.

File: pkg/orm/orm_raw.go [hunk 1]
```diff
@@ -369,7 +369,15 @@ func (o *rawSet) QueryRow(containers ...interface{}) error {
 							field.Set(mf)
 							field = mf.Elem().FieldByIndex(fi.relModelInfo.fields.pk.fieldIndex)
 						}
-						o.setFieldValue(field, value)
+						if fi.isFielder {
+							fd := field.Addr().Interface().(Fielder)
+							err := fd.SetRaw(value)
+							if err != nil {
+								return fmt.Errorf("set raw error:%s", err)
```
Comment (flycash) [inline pkg/orm/orm_raw.go:376]: What about using `github.com/pkg/errors`, we can change it in the future. I will check this PR this weekend.

Comment (AllenX2018) [reply pkg/orm/orm_raw.go:376]: Sure. But I wonder what's the difference between `errors.New()` and `fmt.Errorf()` ?
